### ISSUE TITLE
Simple Navigation crashing HapMap [Android Pixel 2 API 32]

### ISSUE THREAD

**Issue by aedanmc** [Hap-Map/HapMap#80] opened 2022-05-22 01:15 UTC
**Describe the bug**
Routing to a nearby location (going from 4th Ave and James, Seattle, WA to Smith Tower, Seattle WA) crashes the program.

**Version**
Unknown (Current as of 5/21/22)

**To Reproduce**
1. Open the app from the android emulator home screen
2. Set the location to 4th and James, Seattle, WA using the emulator extended controls.
3. From HapMap, type in "Smith Tower".
4. Select the matching location in Seattle.
5. Select "Start Navigation".

**Actual Results** 
The application got all the way to "Start Navigation" and then a red screen with yellow text that read "package:hap_map/models/directions_model.dart': Failed assertion: line 183 pos 13: 'index < numSteps': is not true. See also: https://flutter.dev/docs/testing/errors" appeared.

**Expected behavior**
I expected to be able to see the first step of the navigation process from 4th and James to Smith Tower.

**Screenshots**
![image](https://user-images.githubusercontent.com/81780113/169673999-b27b3236-01a1-45be-ad06-6809da002154.png)
![image](https://user-images.githubusercontent.com/81780113/169674006-fa270f1b-d48f-4976-9ed9-294a98391f77.png)
![image](https://user-images.githubusercontent.com/81780113/169673972-ec046f01-3677-4c06-bb32-fd354d39936f.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 emulator
 - OS: Android
 - Version: API level 32

**Comment by emilychang9** [comment] 2022-05-23 19:51
I was unable to reproduce this issue on a Pixel 4 API 29. The first step of the navigation process appeared as expected. We will continue attempting to reproduce the error on different configurations. Let us know if you have any questions!

<img width="365" alt="Screen Shot 2022-05-23 at 12 49 32 PM" src="https://user-images.githubusercontent.com/69648669/169895134-364bb3e9-4737-4bd2-939a-38031208e7f7.png">

**Comment by aedanmc** [comment] 2022-05-23 19:55
Thanks for taking a look at this! It could be that I made a mistake in setting up the dev environment or there is a significant difference in functionality between API level 32 on a Pixel 2 and API level 29 on a Pixel 4. Either way, if the bug is not replicable after trying different configurations then maybe it would be good to close this issue and mark it as `wontfix`.

**Comment by emilychang9** [comment] 2022-05-24 20:42
Closing for now, we'll make sure to double check our setup directions and error-catching for the future!

**Closed as completed by emilychang9** 2022-05-24 20:42 UTC
Labels: bug, wontfix
